#Imagem base
FROM gcc:8

#Assinatura
MAINTAINER Rodrigo Martins

#Determina as variáveis que definem a versão do Toolchain
ENV TOOLCHAIN_NAME gcc-arm-none-eabi
ENV TOOLCHAIN_GCC_VERSION 8
ENV TOOLCHAIN_YEAR 2018
ENV TOOLCHAIN_QUARTER q4
ENV TOOLCHAIN_REVISION major
ENV TOOLCHAIN_OS linux
ENV TOOLCHAIN_PACKAGE tar.bz2
ENV TOOLCHAIN_FILE ${TOOLCHAIN_NAME}-${TOOLCHAIN_GCC_VERSION}-${TOOLCHAIN_YEAR}-${TOOLCHAIN_QUARTER}-${TOOLCHAIN_REVISION}-${TOOLCHAIN_OS}.${TOOLCHAIN_PACKAGE}
ENV TOOLCHAIN_DOWNLOAD_URL https://developer.arm.com/-/media/Files/downloads/gnu-rm/${TOOLCHAIN_GCC_VERSION}-${TOOLCHAIN_YEAR}${TOOLCHAIN_QUARTER}/${TOOLCHAIN_FILE}
ENV TOOLCHAIN_FOLDER ${TOOLCHAIN_NAME}-${TOOLCHAIN_GCC_VERSION}-${TOOLCHAIN_YEAR}-${TOOLCHAIN_QUARTER}-${TOOLCHAIN_REVISION}
ENV CC arm-none-eabi-gcc

#Faz download
RUN curl -sSL ${TOOLCHAIN_DOWNLOAD_URL} \
		| tar -xjC /usr/local/bin

#Adiciona o caminho do compilador ao PATH
ENV PATH="${PATH}:/usr/local/bin/${TOOLCHAIN_FOLDER}/bin"

#testa o compilador
RUN ${CC} -v

#Inicia o bash
CMD ["/bin/bash"]

